In [12]:
import sys
sys.path.insert(0, '../src/')

import pandas as pd
import kaggle
import auto_co2 as co2
import importlib
importlib.reload(co2)

#auth_file_path = ''
#df = co2.data.download_and_load_co2_data()
df = co2.data.load_co2_data(filepath='../../data/raw')
df = co2.data.dataviz_preprocess(df)
df['ElectricRange'] = df['ElectricRange'].fillna(0)
df['InnovativeEmissionsReductionWltp'] = df['InnovativeEmissionsReductionWltp'].fillna(0)
df['ElectricConsumption'] = df['ElectricConsumption'].fillna(0)
df = co2.data.standardize_innovtech(df)
df = df.drop(columns=['ID', 'Country', 'ManufacturerName', 'WltpTestMass', 'FuelConsumption', 'RegistrationDate', 'AxleWidthSteering', 'ManufNameOem', 'FuelMode', 'EngineCapacity', 'AxleWidthSteering'])


df = co2.data.conditional_column_update(df, 'CategoryOf', 'm1', 'CategoryOf', 'M1')

Incomplete rows dropped:473981

In [13]:
gb = df.groupby([
    'CommercialName', 
    'FuelType', 
    'CategoryOf', 
    'InnovativeTechnology', 
    'Co2EmissionsWltp', 
    'EnginePower', 
    'ElectricRange',
    'InnovativeEmissionsReductionWltp', 
    'MassRunningOrder', 
    'BaseWheel',
    'Pool'
]).size().reset_index().rename(columns={0: 'Count'})

gb['Share'] = gb['Count'] / gb['Count'].sum()

display(gb.head(10))
print(gb.info())

gb.sort_values(by=['Count'], ascending=False)

,CommercialName,FuelType,CategoryOf,InnovativeTechnology,Co2EmissionsWltp,EnginePower,ElectricRange,InnovativeEmissionsReductionWltp,MassRunningOrder,BaseWheel,Pool,Count,Share
0,---,PETROL,M1,0,132.0,96.0,0.0,0.0,1323.0,2605.0,STELLANTIS,1,1.058635e-07
1,108,PETROL,M1,0,85.0,53.0,0.0,0.0,915.0,2340.0,STELLANTIS,72,7.622171e-06
2,108,PETROL,M1,0,109.0,53.0,0.0,0.0,915.0,2340.0,STELLANTIS,710,7.516308e-05
3,108,PETROL,M1,0,110.0,53.0,0.0,0.0,915.0,2340.0,STELLANTIS,14247,1.508237e-03
4,108,PETROL,M1,0,110.0,53.0,0.0,0.0,930.0,2340.0,STELLANTIS,44,4.657994e-06
5,108,PETROL,M1,0,110.0,53.0,0.0,0.0,956.0,2340.0,STELLANTIS,3,3.175905e-07
6,108,PETROL,M1,0,110.0,53.0,0.0,0.0,1240.0,2340.0,STELLANTIS,107,1.132739e-05
7,108,PETROL,M1,0,111.0,53.0,0.0,0.0,915.0,2340.0,STELLANTIS,11473,1.214572e-03
8,108,PETROL,M1,0,111.0,53.0,0.0,0.0,930.0,2340.0,STELLANTIS,1319,1.396339e-04
9,108,PETROL,M1,0,111.0,53.0,0.0,0.0,965.0,2340.0,STELLANTIS,2428,2.570366e-04

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254925 entries, 0 to 254924
Data columns (total 13 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   CommercialName                    254925 non-null  object
 1   FuelType                          254925 non-null  object
 2   CategoryOf                        254925 non-null  object
 3   InnovativeTechnology              254925 non-null  int64
 4   Co2EmissionsWltp                  254925 non-null  float64
 5   EnginePower                       254925 non-null  float64
 6   ElectricRange                     254925 non-null  float64
 7   InnovativeEmissionsReductionWltp  254925 non-null  float64
 8   MassRunningOrder                  254925 non-null  float64
 9   BaseWheel                         254925 non-null  float64
 10  Pool                              254925 non-null  object
 11  Count                             254925 non-null  int64
 12  Share                             254925 non-null  float64
dtypes: float64(7), int64(2), object(4)
memory usage: 25.3+ MB
None

,CommercialName,FuelType,CategoryOf,InnovativeTechnology,Co2EmissionsWltp,EnginePower,ElectricRange,InnovativeEmissionsReductionWltp,MassRunningOrder,BaseWheel,Pool,Count,Share
49128,C3,PETROL,M1,1,123.0,61.0,0.0,1.9,1055.0,2539.0,STELLANTIS,27691,2.931466e-03
2977,208,PETROL,M1,1,118.0,74.0,0.0,2.1,1165.0,2540.0,STELLANTIS,27266,2.886474e-03
62790,CLIO,PETROL,M1,1,118.0,67.0,0.0,1.9,1157.0,2583.0,RENAULT-NISSAN-MITSUBISHI,24995,2.646058e-03
252163,ZOE,ELECTRIC,M1,0,0.0,51.0,0.0,0.0,1577.0,2588.0,RENAULT-NISSAN-MITSUBISHI,24673,2.611970e-03
195422,SANDERO,PETROL,M1,1,128.0,67.0,0.0,1.8,1171.0,2604.0,RENAULT-NISSAN-MITSUBISHI,19067,2.018499e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...
171161,PICANTO,PETROL,M1,0,122.0,62.0,0.0,0.0,1009.0,1390.0,KIA,1,1.058635e-07
171160,PICANTO,PETROL,M1,0,122.0,62.0,0.0,0.0,983.0,2400.0,KIA,1,1.058635e-07
171174,PICANTO,PETROL,M1,0,123.0,62.0,0.0,0.0,1400.0,2400.0,KIA,1,1.058635e-07
171173,PICANTO,PETROL,M1,0,123.0,62.0,0.0,0.0,1064.0,2400.0,KIA,1,1.058635e-07
75912,DISCOVERY SPORT D165 S AWD AUT,DIESEL,M1G,1,178.0,120.0,0.0,1.8,1949.0,2741.0,TATA-MOTORS,1,1.058635e-07

In [3]:
gb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254775 entries, 0 to 254774
Data columns (total 13 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   CommercialName                    254775 non-null  object
 1   FuelType                          254775 non-null  object
 2   CategoryOf                        254775 non-null  object
 3   InnovativeTechnology              254775 non-null  int64
 4   Co2EmissionsWltp                  254775 non-null  float64
 5   EnginePower                       254775 non-null  float64
 6   ElectricRange                     254775 non-null  float64
 7   InnovativeEmissionsReductionWltp  254775 non-null  float64
 8   MassRunningOrder                  254775 non-null  float64
 9   BaseWheel                         254775 non-null  float64
 10  Pool                              254775 non-null  object
 11  Count                             254775 non-null  int64
 12  Share                             254775 non-null  float64
dtypes: float64(7), int64(2), object(4)
memory usage: 25.3+ MB

In [14]:
gb = co2.data.dummify_all_categoricals(gb, dummy_columns=['Pool', 'FuelType', 'CategoryOf'], should_discretize_electricrange=False)

co2.data.save_processed_data(gb, classification=False, pickle=False)

Data saved to ../data/processed/co2_regression_20240115-231653

In [5]:
gb.sort_values(by=['Count'], ascending=False)

,CommercialName,InnovativeTechnology,Co2EmissionsWltp,EnginePower,ElectricRange,InnovativeEmissionsReductionWltp,MassRunningOrder,BaseWheel,Count,Share,...,FuelType_ETHANOL,FuelType_HYDROGEN,FuelType_LPG,FuelType_NATURALGAS,FuelType_NG,FuelType_PETROL,FuelType_PETROL/ELECTRIC,FuelType_UNKNOWN,CategoryOf_M1,CategoryOf_M1G
209805,SUPERB,0,36.0,115.0,51.0,0.0,1752.0,2836.0,4272,2.191366e-05,...,0,0,0,0,0,0,1,0,1,0
209836,SUPERB,0,39.0,115.0,50.0,0.0,1752.0,2836.0,4272,2.191366e-05,...,0,0,0,0,0,0,1,0,1,0
209835,SUPERB,0,38.0,115.0,63.0,0.0,1752.0,2836.0,4272,2.191366e-05,...,0,0,0,0,0,0,1,0,1,0
209834,SUPERB,0,38.0,115.0,52.0,0.0,1752.0,2836.0,4272,2.191366e-05,...,0,0,0,0,0,0,1,0,1,0
209833,SUPERB,0,38.0,115.0,51.0,0.0,1899.0,2836.0,4272,2.191366e-05,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205544,STONIC/GOLD/UVO/1.25 MPI/MT5/8,1,137.0,61.0,0.0,1.0,1155.0,2580.0,1,5.129603e-09,...,0,0,0,0,0,1,0,0,1,0
205550,STONIC/OE21/1.0 TGDI/MT6/100,1,125.0,73.0,0.0,1.4,1195.0,2580.0,1,5.129603e-09,...,0,0,0,0,0,1,0,0,1,0
205551,STONIC/SILBER LIMITED/1.0 TGDI,1,132.0,73.0,0.0,1.4,1195.0,2580.0,1,5.129603e-09,...,0,0,0,0,0,1,0,0,1,0
72796,D,0,237.0,183.0,0.0,0.0,2695.0,3022.0,1,5.129603e-09,...,0,0,0,0,0,0,0,0,0,1
249498,X6 xDrive 3.0d,0,204.0,195.0,0.0,0.0,2185.0,2975.0,1,5.129603e-09,...,0,0,0,0,0,0,0,0,1,0

In [11]:
gb[gb['CommercialName'] == 'CLIO'].sort_values(by='Count', ascending=False)

,CommercialName,InnovativeTechnology,Co2EmissionsWltp,EnginePower,ElectricRange,InnovativeEmissionsReductionWltp,MassRunningOrder,BaseWheel,Count,Share,...,FuelType_ETHANOL,FuelType_HYDROGEN,FuelType_LPG,FuelType_NATURALGAS,FuelType_NG,FuelType_PETROL,FuelType_PETROL/ELECTRIC,FuelType_UNKNOWN,CategoryOf_M1,CategoryOf_M1G
63054,CLIO,1,130.0,67.0,0.0,1.9,1201.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,1,1,0
61963,CLIO,0,94.0,85.0,0.0,0.0,1264.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,0,1,0
61964,CLIO,0,109.0,63.0,0.0,0.0,1264.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,0,1,0
61965,CLIO,0,109.0,63.0,0.0,0.0,1284.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,0,1,0
63015,CLIO,1,131.0,74.0,0.0,1.0,1187.0,2583.0,1092,0.000006,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61970,CLIO,0,110.0,63.0,0.0,0.0,1272.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,0,1,0
61971,CLIO,0,110.0,63.0,0.0,0.0,1289.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,0,1,0
61972,CLIO,0,110.0,63.0,0.0,0.0,1290.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,0,1,0
61973,CLIO,0,110.0,63.0,0.0,0.0,1293.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,0,1,0
61974,CLIO,0,110.0,63.0,0.0,0.0,1296.0,2583.0,1092,0.000006,...,0,0,0,0,0,0,0,0,1,0